apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: blueteam
  name: blueteam
apiVersion: v1
---
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: redteam
  name: redteam


